language:
  - id: "cpp"
    extension: "cpp"
  - id: "c"
    extension: "cpp"
  - id: "python"
    extension: "py"
  - id: "rust"
    extension: "rs"
  - id: "go"
    extension: "go"
  - id: "java"
    extension: "java"
message:
  Correct: "Output is correct"
  Partially Correct: "Output is partially correct"
  Incorrect: "Output is incorrect"
  Time Limit Exceeded: "Judge killed: time limit exceeded"
  Memory Limit Exceeded: "Judge killed: memory limit exceeded"
  Runtime Error: "Judge killed: runtime error"
  Signal Error: "Judge killed: program died on a signal"
  Judge Error: "Judge killed: internal error"
