#!/usr/bin/python3
import sys

full_score = float(sys.argv[1])
score = [float(i) for i in sys.argv[2:]]

result = -1

for i in score:
    if result == -1 or i < result:
        result = i
print(result * full_score / 100)
