[env]
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
DATABASE_USERNAME = "postgres"
DATABASE_PASSWORD = "password"
DATABASE_NAME = "db"
RABBITMQ_HOST = "localhost"
RABBITMQ_VHOST = "/"
RABBITMQ_PORT = "5432"
RABBITMQ_USERNAME = "user"
RABBITMQ_PASSWORD = "password"
RABBITMQ_ENV = "prod"
RUST_LOG = "debug"

ISOLATE_PATH="/usr/local/bin/isolate"
ALTERNATIVE_PATH="/etc/alternatives"
TEMPORARY_PATH="/tmp"
BASE_PATH="./example"