#!/usr/bin/python3
import os
import subprocess
import sys

base_dir = sys.argv[1]
compile_files = []
for i in range(2, len(sys.argv)):
    compile_files.append(sys.argv[i])

output_path = os.path.join(base_dir, "bin")
# NOTE: rustc only accepts the .rs file containing main.rs so make sure it is at position 0
cmd = ["/usr/bin/rustc", "-O", "-o", output_path, compile_files[0]]

capture = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

f = open(os.path.join(base_dir, "compileMsg"), "w")
f.write(capture.stdout.decode("utf-8"))
f.close()
print(capture.returncode)
print(output_path)
